services:
  db:
    container_name: nextcloud-db
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_db
      MYSQL_USER_FILE: /run/secrets/mysql_user
    secrets:
      - mysql_root_password
      - mysql_password
      - mysql_db
      - mysql_user
    networks:
      - traefik-network

  redis:
    image: redis:latest
    container_name: nextcloud-cache
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - cache:/data
    networks:
      - traefik-network

  app:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker-cifs/:/mnt/docker-cifs
    environment:
      MYSQL_HOST: db
      REDIS_HOST: redis
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_db
      MYSQL_USER_FILE: /run/secrets/mysql_user
    depends_on:
      - db
      - redis
    secrets:
      - mysql_password
      - mysql_db
      - mysql_user
    labels:
      traefik.enable: true
      traefik.http.routers.nextcloud.rule: Host(`nextcloud.azunyan.io`)
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.tls.certresolver: route53
    networks:
      - traefik-network

volumes:
  db:
  nextcloud:
  cache:


secrets:
  mysql_db:
    file: /mnt/docker-cifs/ubuntu/compose/nextcloud/.MYSQL_DATABASE
  mysql_user:
    file: /mnt/docker-cifs/ubuntu/compose/nextcloud/.MYSQL_USER
  mysql_password:
    file: /mnt/docker-cifs/ubuntu/compose/nextcloud/.MYSQL_PASSWORD
  mysql_root_password:
    file: /mnt/docker-cifs/ubuntu/compose/nextcloud/.MYSQL_ROOT_PASSWORD

networks:
  traefik-network:
    external: true
