services:
  whoami:
    image: traefik/whoami
    container_name: whoami

    labels:
      traefik.enable: true
      traefik.http.routers.whoami.rule: Host(`whoami.azunyan.io`)
      traefik.http.routers.whoami.entrypoints: websecure
      traefik.http.routers.whoami.tls.certresolver: route53
    restart: always
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
