services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    tty: true
    stdin_open: true
    restart: always
    environment:
      EULA: true
      VERSION: 1.18.1
      DIFFICULTY: normal
      SERVER_NAME: AzunyanServer
      TYPE: FORGE
      FORGEVERSION: 39.0.79
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      TZ: Asia/Tokyo
      ENABLE_RCON: true
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: 28016
      ENABLE_QUERY: true
      ENABLE_STATUS: true
      OPS: ${OPS}
      USE_AIKAR_FLAGS: true
      MEMORY: 20G
      USE_LARGE_PAGES: true
    networks:
      - traefik-network
    volumes:
      - mc_forge:/data
      - /mnt/docker-cifs/ubuntu/compose/minecraft/mods:/mods:ro

volumes:
  mc_forge:


networks:
  traefik-network:
    external: true
