services:
  joplin-db:
    image: postgres:13
    volumes:
      - joplin-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks:
      - traefik-network

  joplin-app:
    image: joplin/server:latest
    depends_on:
      - joplin-db
    restart: unless-stopped
    environment:
      APP_PORT: 22300
      APP_BASE_URL: https://joplin.azunyan.io
      DB_CLIENT: pg
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: 5432
      POSTGRES_HOST: joplin-db
      MAILER_ENABLED: ${MAILER_ENABLED}
      MAILER_HOST: ${MAILER_HOST}
      MAILER_PORT: ${MAILER_PORT}
      MAILER_SECURITY: ${MAILER_SECURITY}
      MAILER_AUTH_USER: ${MAILER_AUTH_USER}
      MAILER_AUTH_PASSWORD: ${MAILER_AUTH_PASSWORD}
      MAILER_NOREPLY_NAME: ${MAILER_NOREPLY_NAME}
      MAILER_NOREPLY_EMAIL: ${MAILER_NOREPLY_EMAIL}
    labels:
      traefik.enable: true
      traefik.http.routers.joplin.rule: Host(`joplin.azunyan.io`)
      traefik.http.routers.joplin.entrypoints: websecure
      traefik.http.services.joplin.loadbalancer.server.port: 22300
      traefik.http.routers.joplin.tls.certresolver: route53
    networks:
      - traefik-network

volumes:
  joplin-data:


networks:
  traefik-network:
    external: true
