http:
  routers:
    truenas:
      entryPoints:
        - websecure
      rule: Host(`truenas.azunyan.io`)
      service: truenas
      tls:
        certResolver: route53
    nvr510:
      entryPoints:
        - websecure
      rule: Host(`nvr510.azunyan.io`)
      service: nvr510
      tls:
        certResolver: route53
  services:
    truenas:
      loadBalancer:
        servers:
        - url: "http://192.168.100.15/ui/sessions/signin"
    nvr510:
      loadBalancer:
        servers:
        - url: "http://192.168.100.1/dashboard"